### ISSUE TITLE
How to send target point to avoidance node using script

### ISSUE THREAD

**Issue by pirate-lofy** [PX4/PX4-Avoidance#607]
I'm trying to make the drone fly to a certain point (without collision) without using QGroundController but using a script.
I'm trying to test this in simulation first..
I do not have a solid understanding about what I should do but I tried to use MavSDK and it run with Gazebo only, when I tried to run the avoidance node then run the MavSDK script it couldn't connect to the drone. 
If anyone has a better insight about what is the way to do that, please tell me.

**Comment by GeneralAdmin** [comment]
I don't know what do you want to do, but you can publish a topic in a console like:

 rostopic pub -r 20 /move_base_simple/goal  geometry_msgs/PoseStamped  '{header: {stamp: now, frame_id: "map"}, pose: {position: {x: 110.0, y: 20.0, z: 30.0}, orientation: {w: 1.0}}}'

Where X,Y is the desired position
