### ISSUE TITLE
RLException: [global_planner_stereo.launch] is neither a launch file in package [global_planner] nor is [global_planner] a launch file name

### ISSUE THREAD

**Issue by pirate-lofy** [PX4/PX4-Avoidance#610]
When I run this command 
`roslaunch global_planner global_planner_stereo.launch` 
it produces the following error
```
RLException: [global_planner_stereo.launch] is neither a launch file in package [global_planner] nor is [global_planner] a launch file name
The traceback for the exception was written to the log file
```
the same error occurs for global_planner , local_planner and safe_landing_planner (all avoidance package).

when I search for ros packages available I can not find any avoidance packages.. and when using 
`rospack find global_planner` 
the result be 
`[rospack] Error: package 'global_planner' not found`

Although all other ros packages located inside catkin_ws/src directory are available.
I reinstalled avoidance and Fimeware (and build catkin) many times but I had no luck.

**Comment by MertEgeCAN** [comment]
Did you pull the repository into your `catkin_ws/src` and compiled it with `catkin_make` or `catkin build`? Then sourced the `catkin_ws/devel/setup.bash` in your terminal or in `.bashrc`?

**Comment by pirate-lofy** [comment]
I used catkin build and sourced the setup.bash file

**Comment by pirate-lofy** [comment]
Solved..
I found that when using catkin build it produces this kind of errors, so when using catkin_make these errors disappear.

**Comment by zh-pang** [comment]
I use catkin_make,it still exists.
