### ISSUE TITLE
can't not repeat the successful local_planner simulation.

### ISSUE THREAD

**Issue by darkasassin44** [PX4/PX4-Avoidance#618]
- ASUS ROG Zephyrus(10th i7 - 8 cores, 16GB RAM, RTX 2070 Max-Q)
- Ubuntu 18.04LTS, ROS Melodic installed.

I have been struggling to represent the SITL with local planner for a few weeks.
First, I'm a new to ROS.
I'd just followed this instruction, and did the SITL at the first time for all the three launch files, `local_planner_stereo`, `local_planner_depth_camera`, and `local_planner_sitl_3cam` with QGroundControl.
From the beginning, I put the variables below to the ~/catkin_ws/devel/setup.bash file.
```
# Set Gazebo environment variables
. ~/Firmware/Tools/setup_gazebo.bash ~/Firmware ~/Firmware/build/px4_sitl_default
export ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}:~/Firmware
export GAZEBO_MODEL_PATH=${GAZEBO_MODEL_PATH}:~/catkin_ws/src/avoidance/avoidance/sim/models:~/catkin_ws/src/avoidance/avoidance/sim/worlds
```

https://user-images.githubusercontent.com/54735854/103171799-6614db00-4892-11eb-931f-8ecef90a6dd9.mp4

I have 3 ubuntu machines, and all of the three laptops are showing same problem.

So I chose to start from beginning, removed 'avoidance' package from /catkin_ws, and /Firmware from my /home directory.
But in the building gazebo simulation section, when I did `make px4_sitl_default gazebo`, I could see the multiple vehicles on gazebo as below.
![Screenshot from 2020-12-27 21-52-00](https://user-images.githubusercontent.com/54735854/103171961-5ba71100-4893-11eb-9e6d-026564dfc53e.png)

lbd_song@lbd-gcs:~$ roslaunch local_planner local_planner_depth-camera.launch 
... logging to /home/lbd_song/.ros/log/21e44136-484d-11eb-84b3-e0d4e8ff40e7/roslaunch-lbd-gcs-12904.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:46773/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /local_planner_nodelet/goal_x_param: 17
 * /local_planner_nodelet/goal_y_param: 15
 * /local_planner_nodelet/goal_z_param: 3
 * /local_planner_nodelet/pointcloud_topics: ['/camera/depth/p...
 * /local_planner_nodelet/world_name: /home/lbd_song/ca...
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: ROLL_180
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: ROLL_180
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: ROLL_180
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: ROLL_180
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: udp://:14540@loca...
 * /mavros/gcs_url: 
 * /mavros/global_position/frame_id: fcu
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: fcu_utm
 * /mavros/global_position/tf/frame_id: local_origin
 * /mavros/global_position/tf/send: False
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.0003490659 // 0...
 * /mavros/imu/frame_id: fcu
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: local_origin
 * /mavros/local_position/tf/child_frame_id: fcu
 * /mavros/local_position/tf/frame_id: local_origin
 * /mavros/local_position/tf/send: True
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: False
 * /mavros/mocap/use_tf: True
 * /mavros/odometry/fcu/odom_child_id_des: base_link
 * /mavros/odometry/fcu/odom_parent_id_des: map
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_throttle: False
 * /mavros/setpoint_attitude/tf/child_frame_id: attitude
 * /mavros/setpoint_attitude/tf/frame_id: local_origin
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 10.0
 * /mavros/setpoint_position/tf/child_frame_id: setpoint
 * /mavros/setpoint_position/tf/frame_id: local_origin
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/vibration/frame_id: vibration
 * /mavros/vision_pose/tf/child_frame_id: vision
 * /mavros/vision_pose/tf/frame_id: local_origin
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: False
 * /rosdistro: melodic
 * /rosversion: 1.14.10
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    local_planner_manager (nodelet/nodelet)
    local_planner_nodelet (nodelet/nodelet)
    mavros (mavros/mavros_node)
    rqt_reconfigure (rqt_reconfigure/rqt_reconfigure)
    rviz (rviz/rviz)
    sitl_0 (px4/px4)
    spawn_model (gazebo_ros/spawn_model)
    tf_depth_camera (tf/static_transform_publisher)

auto-starting new master
process[master]: started with pid [12914]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 21e44136-484d-11eb-84b3-e0d4e8ff40e7
process[rosout-1]: started with pid [12925]
started core service [/rosout]
process[tf_depth_camera-2]: started with pid [12933]
process[rqt_reconfigure-3]: started with pid [12934]
process[sitl_0-4]: started with pid [12942]
INFO  [px4] Creating symlink /home/lbd_song/Firmware/build/px4_sitl_default/etc -> /home/lbd_song/.ros/etc

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

INFO  [px4] Calling startup script: /bin/sh etc/init.d-posix/rcS 0
process[mavros-5]: started with pid [12955]
Info: found model autostart file as SYS_AUTOSTART=1015
INFO  [param] selected parameter default file eeprom/parameters_1015
[param] Loaded: eeprom/parameters_1015
process[gazebo-6]: started with pid [12966]
process[spawn_model-7]: started with pid [12977]
process[local_planner_manager-8]: started with pid [12989]
process[local_planner_nodelet-9]: started with pid [12999]
INFO  [dataman] Unknown restart, data manager file './dataman' size is 11798680 bytes
process[rviz-10]: started with pid [13002]
INFO  [simulator] Waiting for simulator to accept connection on TCP port 4560
[ INFO] [1609078169.221061602]: Loading nodelet /local_planner_nodelet of type LocalPlannerNodelet to manager local_planner_manager with the following remappings:
[ INFO] [1609078169.224014105]: waitForService: Service [/local_planner_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1609078169.226580157]: Initializing nodelet with 16 worker threads.
[ INFO] [1609078169.245511813]: waitForService: Service [/local_planner_manager/load_nodelet] is now available.
[ INFO] [1609078169.253951156]: FCU URL: udp://:14540@localhost:14557
[ INFO] [1609078169.256290220]: udp0: Bind address: 0.0.0.0:14540
[ INFO] [1609078169.256364670]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1609078169.256462788]: GCS bridge disabled
[ INFO] [1609078169.267111903]: Plugin 3dr_radio loaded
[ INFO] [1609078169.269131829]: Plugin 3dr_radio initialized
[ INFO] [1609078169.269184039]: Plugin actuator_control loaded
[ INFO] [1609078169.272138472]: Plugin actuator_control initialized
[ INFO] [1609078169.275139268]: Plugin adsb loaded
[ INFO] [1609078169.280295458]: Plugin adsb initialized
[ INFO] [1609078169.280369303]: Plugin altitude loaded
[ INFO] [1609078169.282525489]: Plugin altitude initialized
[ INFO] [1609078169.282599639]: Plugin cam_imu_sync loaded
[ INFO] [1609078169.283543644]: Plugin cam_imu_sync initialized
[ INFO] [1609078169.283608332]: Plugin command loaded
[ INFO] [1609078169.290192166]: Plugin command initialized
[ INFO] [1609078169.290266648]: Plugin companion_process_status loaded
[ INFO] [1609078169.292312344]: Plugin companion_process_status initialized
[ INFO] [1609078169.292380530]: Plugin debug_value loaded
[ INFO] [1609078169.296636853]: Plugin debug_value initialized
[ INFO] [1609078169.296657956]: Plugin distance_sensor blacklisted
[ INFO] [1609078169.296709412]: Plugin esc_status loaded
[ INFO] [1609078169.297622113]: Plugin esc_status initialized
[ INFO] [1609078169.297685079]: Plugin fake_gps loaded
[ INFO] [1609078169.309187595]: Plugin fake_gps initialized
[ INFO] [1609078169.309298847]: Plugin ftp loaded
[ INFO] [1609078169.317352989]: Plugin ftp initialized
[ INFO] [1609078169.317456900]: Plugin global_position loaded
[ INFO] [1609078169.321098932]: rviz version 1.13.15
[ INFO] [1609078169.321160348]: compiled against Qt version 5.9.5
[ INFO] [1609078169.321170269]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1609078169.334306583]: Plugin global_position initialized
[ INFO] [1609078169.334386135]: Plugin gps_rtk loaded
[ INFO] [1609078169.336035552]: Forcing OpenGl version 0.
[ INFO] [1609078169.337357595]: Plugin gps_rtk initialized
[ INFO] [1609078169.337417752]: Plugin gps_status loaded
[ INFO] [1609078169.339558316]: Plugin gps_status initialized
[ INFO] [1609078169.339650842]: Plugin hil loaded
[ INFO] [1609078169.349063528]: Plugin hil initialized
[ INFO] [1609078169.349194364]: Plugin home_position loaded
[ INFO] [1609078169.351065744]: Plugin home_position initialized
[ INFO] [1609078169.351175481]: Plugin imu loaded
[ INFO] [1609078169.354982341]: Plugin imu initialized
[ INFO] [1609078169.355077966]: Plugin landing_target loaded
[ INFO] [1609078169.360145765]: Plugin landing_target initialized
[ INFO] [1609078169.360224515]: Plugin local_position loaded
[ INFO] [1609078169.363419839]: Plugin local_position initialized
[ INFO] [1609078169.363487192]: Plugin log_transfer loaded
[ INFO] [1609078169.364805775]: Plugin log_transfer initialized
[ INFO] [1609078169.364863158]: Plugin manual_control loaded
[ INFO] [1609078169.366277062]: Plugin manual_control initialized
[ INFO] [1609078169.366333091]: Plugin mocap_pose_estimate loaded
[ INFO] [1609078169.368255794]: Plugin mocap_pose_estimate initialized
[ INFO] [1609078169.368322261]: Plugin mount_control loaded
[ INFO] [1609078169.370156065]: Plugin mount_control initialized
[ INFO] [1609078169.370225125]: Plugin obstacle_distance loaded
[ INFO] [1609078169.371741931]: Plugin obstacle_distance initialized
[ INFO] [1609078169.371803287]: Plugin odom loaded
[ INFO] [1609078169.374246466]: Plugin odom initialized
[ INFO] [1609078169.374308555]: Plugin onboard_computer_status loaded
[ INFO] [1609078169.375633844]: Plugin onboard_computer_status initialized
[ INFO] [1609078169.375713511]: Plugin param loaded
[ INFO] [1609078169.377169431]: Plugin param initialized
[ INFO] [1609078169.377261233]: Plugin play_tune loaded
[ INFO] [1609078169.378749239]: Plugin play_tune initialized
[ INFO] [1609078169.378847349]: Plugin px4flow loaded
[ INFO] [1609078169.387338250]: Plugin px4flow initialized
[ INFO] [1609078169.387378319]: Plugin rangefinder blacklisted
[ INFO] [1609078169.387458474]: Plugin rc_io loaded
[ INFO] [1609078169.389404667]: Plugin rc_io initialized
[ INFO] [1609078169.389429399]: Plugin safety_area blacklisted
[ INFO] [1609078169.389505266]: Plugin setpoint_accel loaded
[ INFO] [1609078169.391172849]: Plugin setpoint_accel initialized
[ INFO] [1609078169.391259900]: Plugin setpoint_attitude loaded
[ INFO] [1609078169.395586074]: Plugin setpoint_attitude initialized
[ INFO] [1609078169.395752123]: Plugin setpoint_position loaded
[ INFO] [1609078169.404075226]: Plugin setpoint_position initialized
[ INFO] [1609078169.404181716]: Plugin setpoint_raw loaded
[ INFO] [1609078169.408512986]: Plugin setpoint_raw initialized
[ INFO] [1609078169.408600139]: Plugin setpoint_trajectory loaded
[ INFO] [1609078169.410880784]: Plugin setpoint_trajectory initialized
[ INFO] [1609078169.410975905]: Plugin setpoint_velocity loaded
[ INFO] [1609078169.413734342]: Plugin setpoint_velocity initialized
[ INFO] [1609078169.413843790]: Plugin sys_status loaded
[ INFO] [1609078169.419610070]: Plugin sys_status initialized
[ INFO] [1609078169.419718375]: Plugin sys_time loaded
[ INFO] [1609078169.422984344]: TM: Timesync mode: MAVLINK
[ INFO] [1609078169.423979943]: Plugin sys_time initialized
[ INFO] [1609078169.424054952]: Plugin trajectory loaded
[ INFO] [1609078169.427651152]: Plugin trajectory initialized
[ INFO] [1609078169.427729640]: Plugin vfr_hud loaded
[ INFO] [1609078169.428136793]: Plugin vfr_hud initialized
[ INFO] [1609078169.428156846]: Plugin vibration blacklisted
[ INFO] [1609078169.428210427]: Plugin vision_pose_estimate loaded
[ INFO] [1609078169.433454505]: Plugin vision_pose_estimate initialized
[ INFO] [1609078169.433543364]: Plugin vision_speed_estimate loaded
[ INFO] [1609078169.435768975]: Plugin vision_speed_estimate initialized
[ INFO] [1609078169.435847358]: Plugin waypoint loaded
[ INFO] [1609078169.438501782]: Plugin waypoint initialized
[ INFO] [1609078169.438522156]: Plugin wheel_odometry blacklisted
[ INFO] [1609078169.438587926]: Plugin wind_estimation loaded
[ INFO] [1609078169.438948788]: Plugin wind_estimation initialized
[ INFO] [1609078169.438968683]: Autostarting mavlink via USB on PX4
[ INFO] [1609078169.439001795]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1609078169.439016129]: Built-in MAVLink package version: 2020.12.12
[ INFO] [1609078169.439044690]: Known MAVLink dialects: common ardupilotmega ASLUAV all autoquad icarous matrixpilot paparazzi standard uAvionix ualberta
[ INFO] [1609078169.439060719]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[gazebo-6] process has died [pid 12966, exit code 255, cmd /opt/ros/melodic/lib/gazebo_ros/gzserver -e ode /home/lbd_song/catkin_ws/src/avoidance/avoidance/sim/worlds/simple_obstacle.world __name:=gazebo __log:=/home/lbd_song/.ros/log/21e44136-484d-11eb-84b3-e0d4e8ff40e7/gazebo-6.log].
log file: /home/lbd_song/.ros/log/21e44136-484d-11eb-84b3-e0d4e8ff40e7/gazebo-6*.log
[ INFO] [1609078169.722340991]: Stereo is NOT SUPPORTED
[ INFO] [1609078169.722418897]: OpenGl version: 4.6 (GLSL 4.6).
[INFO] [1609078169.896500, 0.000000]: Loading model XML from Gazebo Model Database
[INFO] [1609078169.897587, 0.000000]: Waiting for service /gazebo/spawn_sdf_model
[ERROR] [1609078174.312030283]: PR: Unknown parameter to get: MPC_ACC_HOR
[ERROR] [1609078174.313438738]: PR: Unknown parameter to get: MPC_ACC_DOWN_MAX
[ERROR] [1609078174.314867259]: PR: Unknown parameter to get: MPC_ACC_UP_MAX
[ERROR] [1609078174.316075358]: PR: Unknown parameter to get: MPC_XY_CRUISE
[ERROR] [1609078174.317348394]: PR: Unknown parameter to get: MPC_Z_VEL_MAX_DN
[ERROR] [1609078174.318671800]: PR: Unknown parameter to get: MPC_Z_VEL_MAX_UP
[ERROR] [1609078174.319937120]: PR: Unknown parameter to get: CP_DIST
[ERROR] [1609078174.321179755]: PR: Unknown parameter to get: MPC_LAND_SPEED
[ERROR] [1609078174.322409055]: PR: Unknown parameter to get: MPC_JERK_MAX
[ERROR] [1609078174.323600600]: PR: Unknown parameter to get: NAV_ACC_RAD
[ERROR] [1609078174.324799121]: PR: Unknown parameter to get: MPC_YAWRAUTO_MAX

![Screenshot from 2020-12-27 23-09-42](https://user-images.githubusercontent.com/54735854/103172732-d45c9c00-4898-11eb-88e5-b7e224d517ac.png)

Now, I cannot figure out what is wrong.
If anyone knows about this problem, or needs more information, please let me know what should I do.

1. I could find a stack of multiple vehicle. To remove this, I did `make clean` in /Firmware, but nothing changed. How can I fix it?
2. If something wrong with my environment setup, please tell me how to fix.
3. With my low-price laptop(i5-10xxx, 8GB RAM, Intel Iris Graphics), I cannot spawn the drone in this simulation. Is it related to the poor resources?

**Comment by darkasassin44** [comment]
I couldn't find out the solution, and reinstall the whole ubuntu.
Everything was fine. I think that there was something wrong with my installation.
`[ERROR] [1609078174.324799121]: PR: Unknown parameter to get:` error was RAM problem.

**Comment by Adhithiyan03** [comment]
How to run the local planner in airsim
