### ISSUE TITLE
OBSTACLE_DISTANCE does not cosider 3D space

### ISSUE THREAD

**Issue by b0b023** [PX4/PX4-Avoidance#622]
Currently OBSTACLE_DISTANCE assumes that the vehicle is moving more or less on a 3D plane and obstacles distances can be provided.
It seems there is no way to provide obstacle distances directly below or above the vehicle. This is often the case in UAV inspection missions.

Example: RGB-D sensor mounted to look straight up and straight down could provide critical obstacle information but it is not possible using the current OBSTACLE messages.

**Comment by baumanta** [comment]
This is true, but it is not an issue. We chose the algorithm to fit the use cases we were considering at the time. Feel free to implement another one and contribute ;)
