### ISSUE TITLE
Add Intel Realsense D435i to iris_realsense model

### ISSUE THREAD

**Issue by Adidushi** [PX4/PX4-Avoidance#630]
I would like to run the package in a simulation with an intel d435i, and I noticed there's an existing iris_realsense.sdf model, but using the older 200 series intel camera. How can I switch it out for the newer version?

**Comment by TheBigTicket13** [comment]
You can't switch to D435i just like that. You should model your camera first. You can do this in .sdf file (or .urdf). If you are using iris_realsense.sdf you should change part of code in which camera is defined to new definiton. You can also do it in iris.sdf file. This might be good references on how to do it: [gazebo plugins](http://gazebosim.org/tutorials?tut=ros_gzplugins), [RealSense model](https://github.com/intel/gazebo-realsense/blob/master/models/realsense_camera/model.sdf)
