### ISSUE TITLE
Where can i buy it?

### ISSUE THREAD

**Issue by yxt916** [PX4/PX4-Avoidance#635]
Intel® Aero Ready to Fly is not selling anymore, so where can i buy the whole thing?

**Comment by Jaeyoung-Lim** [comment]
@yxt916 The product is discontinued, and this project doesn't necessarily work with the intel aero

Could you clarify why you want to buy the platform?

**Comment by yxt916** [comment]
> @yxt916 The product is discontinued, and this project doesn't necessarily work with the intel aero
> 
> Could you clarify why you want to buy the platform?

Because the localplanner is tested in this drone，if i use the same drone, it will be easy .
Here：
https://github.com/PX4/PX4-Avoidance#companion-computer"
“
Tested models:
local planner: Intel NUC, Jetson TX2, Intel Atom x7-Z8750 (built-in on Intel® Aero RTF drone)
"

**Comment by Jaeyoung-Lim** [comment]
@yxt916 I would say a better supported vehicle is http://www.holybro.com/product/px4-vision/
