### ISSUE TITLE
About using GPS

### ISSUE THREAD

**Issue by yxt916** [PX4/PX4-Avoidance#637]
Is it necessary for the localplanner or the globalplanner to use theGPS?
I want to test indoor, so i can't use GPS. But there have little information about these planners use gps or not.

**Comment by TSC21** [comment]
For using Avoidance, you need a source of position, being it provided by GPS or a local position system / visual odometry framework. Specifically for navigation through waypoints (Mission mode), you need GPS for that. For indoors, you cannot use mission mode (rather you can use offboard control).
