### ISSUE TITLE
PX4-avoidance ROS2 current status

### ISSUE THREAD

**Issue by a-sheikh** [PX4/PX4-Avoidance#648]
Hi,

I wanted to use PX4 avoidance with ROS2 dashing. There is a ros2 branch, but there is no documentation, or current status. 

How far along is the migration; is the migration done? Which version of ROS2 is supported?

any help would be appreciated.

**Comment by TSC21** [comment]
The only effort right now in this regard is happening here: https://github.com/PX4/PX4-Avoidance/pull/626. Other than that, this branch is currently stale with no plans to continue it. Though people are free to continue the effort and contribute if they want.
