### ISSUE TITLE
Hardware implementation Generate launch file is deprecated

### ISSUE THREAD

**Issue by Samyak-ja-in** [PX4/PX4-Avoidance#679]
I was trying to implement local planner on hardware but I am unable to generate launch file as the file 
generate_launchfile.sh
is deprecated
Thanks!

**Comment by Jaeyoung-Lim** [comment]
@Samyak-ja-in the lauchfile generation script is not necessary to run the package on hardware

**Comment by Samyak-ja-in** [comment]
So how to run it on hardware I am stuck can you share me the launch file to launch

**Comment by Jaeyoung-Lim** [comment]
@Samyak-ja-in You need to write a launchfile that fits your hardware. The launchfile generation does not solve this problem for you

**Comment by Samyak-ja-in** [comment]
I am also unable to find px4_config.yaml at the given path
\$(find local_planner)/resource/px4_config.yaml"

**Comment by Jaeyoung-Lim** [comment]
@Samyak-ja-in which file is using that path?

**Comment by Samyak-ja-in** [comment]
@Jaeyoung-Lim generate_launchfile_deprecated.sh
I am trying to generate launch file using that deprecated file.
I solved it by copying px4_config.yaml from global_planner

**Comment by Samyak-ja-in** [comment]
But now getting another error after launching avoidance.launch file

**Comment by Jaeyoung-Lim** [comment]
@Samyak-ja-in The launchfile generation script is deprecated therefore is not expected to work. The file you mentioned had been moved previously, but the launchfile generation script had not been updated since it has been deprecated.

If you have other issues please post a new issue
